# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('armorClass', models.CharField(max_length=100)),
                ('armorType', models.CharField(choices=[('Light', 'Light armor'), ('Medium', 'Medium armor'), ('Heavy', 'Heavy armor')], max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('stealth', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=200)),
                ('magical', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArmorStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('charisma', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
                ('perception', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('willpower', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='resources.Armor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
