# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('armorClass', models.CharField(max_length=100)),
                ('armorType', models.CharField(choices=[('Light', 'Light armor'), ('Medium', 'Medium armor'), ('Heavy', 'Heavy armor')], max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('stealth', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=200)),
                ('magical', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=200)),
                ('armors', models.ManyToManyField(related_name='magical_properties', to='resources.Armor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('charisma', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
                ('perception', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('willpower', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('damage', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='magicproperty',
            name='weapons',
            field=models.ManyToManyField(related_name='magical_properties', to='resources.Weapon'),
        ),
    ]
